### PR TITLE
Added icons for Twitch and Hackmd

### PR DESCRIPTION
**Pull request by mathiasbockwoldt**
This makes a more beautiful footer of the RSHour website.

Slight disadvantage is that the minima social icons file had to be included in the assets to overwrite the default icon file.

### CODE REVIEW

**Comment by rkdarst** [comment]
This is great!  I had wanted this, but didn't have time to figure out how to do it properly.  What tools did you use to this?

Would you want to also submit it to upstream Minima?  I'm not even sure about policies on external service icons like this, but it seems they have plenty of others so I guess it's OK.  Of course, it seems Minima hasn't released in a while... so we embed other stuff, too.  I guess we'll have to embed this as well.

**Comment by mathiasbockwoldt** [comment]
Thank you! I used only a text editor (geany) for this. I was lucky to find both icons as single path svg files and could simply copy the paths to the `minima-social-icons.svg` and add some `<symbol>` stuff that I copied from the other logos in the file. I did some manual testing with `jekyll serve` locally to see whether the sizes and margins are correct.

Logos are from
- Twitch: https://seeklogo.com/vector-logo/274042/twitch
- Hackmd: https://github.com/encharm/Font-Awesome-SVG-PNG/blob/master/black/svg/file-text.svg

I guess, I could submit one pull request per icon to minima. But it looks like their response time is relatively low at the moment, so I don't know when it would be included. There are some open pull requests for other icons (tumblr and goodreads).

**Comment by rkdarst** [comment]
Thanks for the info on how this works.

Let's take this, and I can try to remember to re-submit to upstream sometime later, once it seems to be useful to do.  I'll credit you and this PR.  Do you agree to the Minima license?

**Comment by mathiasbockwoldt** [comment]
Yes, sure, I agree to the Minima license. MIT is my favourite license 😉 
Thanks for accepting 😃

**Comment by bast** [comment]
Thanks a lot Mathias!

**Pull request merged**
