### PR TITLE
change target branch from master to gh-pages

### PR DESCRIPTION
**Pull request by bast**
this is part of #45

### CODE REVIEW

**Comment by rkdarst** [comment]
I guess we do this, update the pages branch in settings, then rename source to main?, then update default branch in github?

**Comment by bast** [comment]
Yes, so there might be few minutes weirdness. I can do the rest now.

**Comment by bast** [comment]
My plan:
- copy source branch to main, keep source until the rest works just in case i delete something accidentally
- change default branch to main
- adapt workflow to build from main
- wait until it works
- delete "source"

**Comment by bast** [comment]
Sounds good?

**Comment by rkdarst** [comment]
Yes, sounds like what I would do.  I'm interested to hear all the
things that go wrong or right... good luck!

**Comment by bast** [comment]
Went fine.

**Pull request merged**
